import { nanoid } from 'nanoid';
import { Player } from '../shared/schema';

// Temporary file to generate players with height/weight data
export function createLakersPlayers(lakersTeamId: string): Player[] {
  return [
    {
      id: nanoid(),
      name: "LeBron James",
      age: 39,
      position: "SF",
      jerseyNumber: 23,
      teamId: lakersTeamId,
      salary: 47600000,
      contractYears: 2,
      height: 81, // 6'9"
      weight: 250,
      overall: 89,
      offense: 92,
      defense: 85,
      speed: 78,
      shooting: 87,
      threePoint: 82,
      rebounding: 83,
      passing: 91,
      gamesPlayed: 23,
      pointsPerGame: 24.8,
      reboundsPerGame: 7.2,
      assistsPerGame: 7.8,
      status: "active",
      potential: 89,
      morale: 85,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Anthony Davis",
      age: 30,
      position: "PF",
      jerseyNumber: 3,
      teamId: lakersTeamId,
      salary: 43200000,
      contractYears: 3,
      height: 82, // 6'10"
      weight: 253,
      overall: 91,
      offense: 88,
      defense: 94,
      speed: 82,
      shooting: 78,
      threePoint: 71,
      rebounding: 91,
      passing: 75,
      gamesPlayed: 23,
      pointsPerGame: 26.1,
      reboundsPerGame: 12.3,
      assistsPerGame: 2.8,
      status: "active",
      potential: 91,
      morale: 88,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "D'Angelo Russell",
      age: 27,
      position: "PG",
      jerseyNumber: 11,
      teamId: lakersTeamId,
      salary: 18700000,
      contractYears: 2,
      height: 74, // 6'2"
      weight: 193,
      overall: 84,
      offense: 88,
      defense: 79,
      speed: 86,
      shooting: 85,
      threePoint: 87,
      rebounding: 65,
      passing: 82,
      gamesPlayed: 23,
      pointsPerGame: 17.4,
      reboundsPerGame: 3.1,
      assistsPerGame: 6.2,
      status: "active",
      potential: 84,
      morale: 82,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Austin Reaves",
      age: 25,
      position: "SG",
      jerseyNumber: 5,
      teamId: lakersTeamId,
      salary: 12000000,
      contractYears: 4,
      height: 77, // 6'5"
      weight: 197,
      overall: 79,
      offense: 81,
      defense: 76,
      speed: 83,
      shooting: 79,
      threePoint: 81,
      rebounding: 68,
      passing: 77,
      gamesPlayed: 23,
      pointsPerGame: 15.2,
      reboundsPerGame: 4.1,
      assistsPerGame: 5.8,
      status: "active",
      potential: 85,
      morale: 90,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Rui Hachimura",
      age: 26,
      position: "SF",
      jerseyNumber: 15,
      teamId: lakersTeamId,
      salary: 15700000,
      contractYears: 3,
      height: 80, // 6'8"
      weight: 230,
      overall: 77,
      offense: 79,
      defense: 74,
      speed: 81,
      shooting: 76,
      threePoint: 78,
      rebounding: 72,
      passing: 68,
      gamesPlayed: 23,
      pointsPerGame: 13.6,
      reboundsPerGame: 5.2,
      assistsPerGame: 1.4,
      status: "active",
      potential: 82,
      morale: 84,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Jarred Vanderbilt",
      age: 25,
      position: "PF",
      jerseyNumber: 21,
      teamId: lakersTeamId,
      salary: 10700000,
      contractYears: 3,
      height: 81, // 6'9"
      weight: 214,
      overall: 76,
      offense: 68,
      defense: 82,
      speed: 84,
      shooting: 62,
      threePoint: 55,
      rebounding: 78,
      passing: 71,
      gamesPlayed: 23,
      pointsPerGame: 5.2,
      reboundsPerGame: 4.8,
      assistsPerGame: 1.1,
      status: "active",
      potential: 80,
      morale: 86,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Gabe Vincent",
      age: 28,
      position: "PG",
      jerseyNumber: 7,
      teamId: lakersTeamId,
      salary: 11000000,
      contractYears: 3,
      height: 75, // 6'3"
      weight: 200,
      overall: 78,
      offense: 80,
      defense: 76,
      speed: 85,
      shooting: 82,
      threePoint: 84,
      rebounding: 58,
      passing: 79,
      gamesPlayed: 23,
      pointsPerGame: 9.4,
      reboundsPerGame: 2.1,
      assistsPerGame: 4.5,
      status: "active",
      potential: 78,
      morale: 83,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Taurean Prince",
      age: 30,
      position: "SF",
      jerseyNumber: 12,
      teamId: lakersTeamId,
      salary: 4500000,
      contractYears: 1,
      height: 79, // 6'7"
      weight: 218,
      overall: 75,
      offense: 77,
      defense: 73,
      speed: 78,
      shooting: 75,
      threePoint: 78,
      rebounding: 69,
      passing: 68,
      gamesPlayed: 23,
      pointsPerGame: 8.9,
      reboundsPerGame: 2.9,
      assistsPerGame: 1.4,
      status: "active",
      potential: 75,
      morale: 81,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Christian Wood",
      age: 28,
      position: "C",
      jerseyNumber: 35,
      teamId: lakersTeamId,
      salary: 2700000,
      contractYears: 1,
      height: 83, // 6'11"
      weight: 214,
      overall: 79,
      offense: 82,
      defense: 74,
      speed: 75,
      shooting: 80,
      threePoint: 79,
      rebounding: 82,
      passing: 70,
      gamesPlayed: 23,
      pointsPerGame: 12.1,
      reboundsPerGame: 6.2,
      assistsPerGame: 1.8,
      status: "active",
      potential: 79,
      morale: 87,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Cam Reddish",
      age: 25,
      position: "SG",
      jerseyNumber: 17,
      teamId: lakersTeamId,
      salary: 2500000,
      contractYears: 1,
      height: 80, // 6'8"
      weight: 217,
      overall: 74,
      offense: 76,
      defense: 72,
      speed: 82,
      shooting: 73,
      threePoint: 76,
      rebounding: 65,
      passing: 69,
      gamesPlayed: 23,
      pointsPerGame: 6.8,
      reboundsPerGame: 2.3,
      assistsPerGame: 1.2,
      status: "active",
      potential: 78,
      morale: 79,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Max Christie",
      age: 21,
      position: "SG",
      jerseyNumber: 10,
      teamId: lakersTeamId,
      salary: 1900000,
      contractYears: 2,
      height: 78, // 6'6"
      weight: 190,
      overall: 69,
      offense: 71,
      defense: 67,
      speed: 79,
      shooting: 70,
      threePoint: 72,
      rebounding: 61,
      passing: 64,
      gamesPlayed: 23,
      pointsPerGame: 4.2,
      reboundsPerGame: 1.8,
      assistsPerGame: 0.9,
      status: "active",
      potential: 82,
      morale: 88,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Dalton Knecht",
      age: 23,
      position: "SG",
      jerseyNumber: 4,
      teamId: lakersTeamId,
      salary: 2500000,
      contractYears: 4,
      height: 78, // 6'6"
      weight: 213,
      overall: 72,
      offense: 75,
      defense: 68,
      speed: 76,
      shooting: 77,
      threePoint: 80,
      rebounding: 63,
      passing: 66,
      gamesPlayed: 23,
      pointsPerGame: 8.1,
      reboundsPerGame: 2.4,
      assistsPerGame: 1.0,
      status: "active",
      potential: 85,
      morale: 92,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Jaxson Hayes",
      age: 24,
      position: "C",
      jerseyNumber: 11,
      teamId: lakersTeamId,
      salary: 2300000,
      contractYears: 2,
      height: 84, // 7'0"
      weight: 220,
      overall: 71,
      offense: 68,
      defense: 74,
      speed: 78,
      shooting: 61,
      threePoint: 42,
      rebounding: 79,
      passing: 59,
      gamesPlayed: 23,
      pointsPerGame: 5.0,
      reboundsPerGame: 4.1,
      assistsPerGame: 0.4,
      status: "active",
      potential: 79,
      morale: 85,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Christian Koloko",
      age: 24,
      position: "C",
      jerseyNumber: 18,
      teamId: lakersTeamId,
      salary: 2000000,
      contractYears: 1,
      height: 85, // 7'1"
      weight: 230,
      overall: 68,
      offense: 62,
      defense: 78,
      speed: 72,
      shooting: 55,
      threePoint: 35,
      rebounding: 81,
      passing: 56,
      gamesPlayed: 23,
      pointsPerGame: 3.2,
      reboundsPerGame: 3.8,
      assistsPerGame: 0.2,
      status: "active",
      potential: 76,
      morale: 82,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Bronny James",
      age: 20,
      position: "PG",
      jerseyNumber: 9,
      teamId: lakersTeamId,
      salary: 1200000,
      contractYears: 4,
      height: 74, // 6'2"
      weight: 210,
      overall: 63,
      offense: 65,
      defense: 68,
      speed: 82,
      shooting: 61,
      threePoint: 64,
      rebounding: 54,
      passing: 71,
      gamesPlayed: 23,
      pointsPerGame: 2.1,
      reboundsPerGame: 1.2,
      assistsPerGame: 1.8,
      status: "active",
      potential: 78,
      morale: 95,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
}

export function createFreeAgents(): Player[] {
  return [
    {
      id: nanoid(),
      name: "Blake Griffin",
      age: 34,
      position: "PF",
      jerseyNumber: 23,
      teamId: null,
      salary: 0,
      contractYears: 0,
      height: 82, // 6'10"
      weight: 250,
      overall: 75,
      offense: 78,
      defense: 70,
      speed: 68,
      shooting: 72,
      threePoint: 74,
      rebounding: 79,
      passing: 76,
      gamesPlayed: 0,
      pointsPerGame: 0,
      reboundsPerGame: 0,
      assistsPerGame: 0,
      status: "active",
      potential: 75,
      morale: 70,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: nanoid(),
      name: "Dwight Howard",
      age: 38,
      position: "C",
      jerseyNumber: 12,
      teamId: null,
      salary: 0,
      contractYears: 0,
      height: 83, // 6'11"
      weight: 265,
      overall: 72,
      offense: 68,
      defense: 85,
      speed: 65,
      shooting: 58,
      threePoint: 30,
      rebounding: 88,
      passing: 62,
      gamesPlayed: 0,
      pointsPerGame: 0,
      reboundsPerGame: 0,
      assistsPerGame: 0,
      status: "active",
      potential: 72,
      morale: 75,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
}